version: '3'
services:
  web:
    build: .
    container_name: "fastapi"
    ports:
      - "80:8000"
    volumes:
      - ./src/:/todo/src
      - ./.env:/todo/.env
    depends_on:
      - db
    networks:
      - todo-network

  db:
    image: postgres
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB={PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres_data:
